-- APARTMENT_ID NULLABLE ONLY IF ROOM IS NULL, FK
-- ROOM_ID NULLABLE, FK
-- MESSAGE_ID NULLABLE, FK
-- MAINT_REQ_ID FK
-- TRANS_REQ_ID FK

-- DROP TABLES/SEQ --
--DROP TABLE EMPLOYEES;
--
--/
-- CREATE TABLES --
CREATE TABLE EMPLOYEES 
(
  EMPLOYEE_ID NUMBER NOT NULL,
  FIRST_NAME VARCHAR2(25) NOT NULL,
  LAST_NAME VARCHAR2(25) NOT NULL,
  USERNAME VARCHAR2(25) NOT NULL UNIQUE,
  PASSWORD VARCHAR2(25) NOT NULL,
  APARTMENT_ID NUMBER,
  MAINT_REQ_ID NUMBER,
  TRANS_REQ_ID NUMBER,
  CONSTRAINT PK_EMPLOYEES PRIMARY KEY (EMPLOYEE_ID)
);

CREATE TABLE APARTMENTS
(
  APARTMENT_ID NUMBER NOT NULL,
  ADDRESS VARCHAR2(50) NOT NULL,
  CITY VARCHAR2(25) NOT NULL,
  STATE VARCHAR2(25) NOT NULL,
  ZIP_CODE VARCHAR2(10) NOT NULL,
  CONSTRAINT PK_APARTMENTS PRIMARY KEY (APARTMENT_ID)
);

CREATE TABLE MESSAGES
(
  MESSAGE_ID NUMBER NOT NULL,
  CHAIN_ID NUMBER NOT NULL,
  MESSAGE VARCHAR2(2000),
  CONSTRAINT PK_MESSAGES PRIMARY KEY (MESSAGE_ID)
);

CREATE TABLE CHAINS
(
  CHAIN_ID NUMBER NOT NULL,
  GROUP_ID_1 NUMBER,
  GROUP_ID_2 NUMBER,
  CONSTRAINT PK_CHAINS PRIMARY KEY (CHAIN_ID)
);

-- AT MOST 6 
CREATE TABLE GROUPS
(
  GROUP_ID NUMBER NOT NULL,
  EMPLOYEE_ID_1 NUMBER,
  EMPLOYEE_ID_2 NUMBER,
  EMPLOYEE_ID_3 NUMBER,
  EMPLOYEE_ID_4 NUMBER,
  EMPLOYEE_ID_5 NUMBER,
  EMPLOYEE_ID_6 NUMBER,
  CONSTRAINT PK_GROUPS PRIMARY KEY (GROUP_ID)
);
-- SENDER_ID POINTS TO EMPLOYEES
CREATE TABLE MAINT_REQS
(
  MAINT_REQ_ID NUMBER NOT NULL,
  MESSAGE_ID NUMBER,
  SENDER_ID NUMBER,
  CONSTRAINT PK_MAINT_REQS PRIMARY KEY (MAINT_REQ_ID)
);

CREATE TABLE TRANS_REQS
(
  TRANS_REQ_ID NUMBER NOT NULL,
  MESSAGE_ID NUMBER,
  SENDER_ID NUMBER,
  CONSTRAINT PK_TRANS_REQS PRIMARY KEY (TRANS_REQ_ID)
);
-- TODO: JOIN TABLES ON MESSAGE_CHAIN RECORDS THAT CONTAIN EMPLOYEE_IDS --
-- TODO: ALTER TABLES
-- TODO: CREATE SEQUENCES/TRIGGERS

-- 