-- APARTMENT_ID NULLABLE ONLY IF ROOM IS NULL, FK
-- ROOM_ID NULLABLE, FK
-- MESSAGE_ID NULLABLE, FK
-- MAINT_REQ_ID FK
-- TRANS_REQ_ID FK

-- DROP TABLES/SEQ --
DROP TABLE TRANS_REQS;
DROP TABLE MAINT_REQS;
DROP TABLE MESSAGES;
DROP TABLE CHAINS;
DROP TABLE GROUPS;
DROP TABLE EMPLOYEES;
DROP TABLE APARTMENTS;
/
DROP SEQUENCE APARTMENT_SEQ;
DROP SEQUENCE CHAIN_SEQ;
DROP SEQUENCE EMPLOYEE_SEQ;
DROP SEQUENCE GROUP_SEQ;
DROP SEQUENCE MAINT_REQ_SEQ;
DROP SEQUENCE MESSAGE_SEQ;
DROP SEQUENCE TRANS_REQ_SEQ;
/
-- CREATE TABLES --
-- FILL 1 = occupied, 0 = vacated
CREATE TABLE EMPLOYEES 
(
  EMPLOYEE_ID NUMBER NOT NULL,
  FIRST_NAME VARCHAR2(25) NOT NULL,
  LAST_NAME VARCHAR2(25) NOT NULL,
  USERNAME VARCHAR2(25) NOT NULL UNIQUE,
  PASSWORD VARCHAR2(25) NOT NULL,
  APARTMENT_ID NUMBER,
  FILL NUMBER DEFAULT 1,
  CONSTRAINT PK_EMPLOYEES PRIMARY KEY (EMPLOYEE_ID)
);

CREATE TABLE APARTMENTS
(
  APARTMENT_ID NUMBER NOT NULL,
  ADDRESS VARCHAR2(50) NOT NULL,
  CITY VARCHAR2(25) NOT NULL,
  STATE VARCHAR2(25) NOT NULL,
  ZIP_CODE VARCHAR2(10) NOT NULL,
  CONSTRAINT PK_APARTMENTS PRIMARY KEY (APARTMENT_ID)
);

CREATE TABLE MESSAGES
(
  MESSAGE_ID NUMBER NOT NULL,
  CHAIN_ID NUMBER NOT NULL,
  MESSAGE VARCHAR2(2000),
  CONSTRAINT PK_MESSAGES PRIMARY KEY (MESSAGE_ID)
);

CREATE TABLE CHAINS
(
  CHAIN_ID NUMBER NOT NULL,
  GROUP_ID_1 NUMBER,
  GROUP_ID_2 NUMBER,
  CONSTRAINT PK_CHAINS PRIMARY KEY (CHAIN_ID)
);

-- AT MOST 6 
CREATE TABLE GROUPS
(
  GROUP_ID NUMBER NOT NULL,
  EMPLOYEE_ID_1 NUMBER,
  EMPLOYEE_ID_2 NUMBER,
  EMPLOYEE_ID_3 NUMBER,
  EMPLOYEE_ID_4 NUMBER,
  EMPLOYEE_ID_5 NUMBER,
  EMPLOYEE_ID_6 NUMBER,
  CONSTRAINT PK_GROUPS PRIMARY KEY (GROUP_ID)
);
-- SENDER_ID POINTS TO EMPLOYEES
CREATE TABLE MAINT_REQS
(
  MAINT_REQ_ID NUMBER NOT NULL,
  MESSAGE_ID NUMBER,
  SENDER_ID NUMBER,
  CONSTRAINT PK_MAINT_REQS PRIMARY KEY (MAINT_REQ_ID)
);

CREATE TABLE TRANS_REQS
(
  TRANS_REQ_ID NUMBER NOT NULL,
  MESSAGE_ID NUMBER,
  SENDER_ID NUMBER,
  CONSTRAINT PK_TRANS_REQS PRIMARY KEY (TRANS_REQ_ID)
);

-- ALTER TABLES --
ALTER TABLE EMPLOYEES ADD CONSTRAINT FK_APARTMENT_ID
  FOREIGN KEY (APARTMENT_ID) REFERENCES APARTMENTS (APARTMENT_ID);

ALTER TABLE MESSAGES ADD CONSTRAINT FK_CHAIN_ID
  FOREIGN KEY (CHAIN_ID) REFERENCES CHAINS (CHAIN_ID);
  
ALTER TABLE CHAINS ADD CONSTRAINT FK_GROUP_ID_1
  FOREIGN KEY (GROUP_ID_1) REFERENCES GROUPS (GROUP_ID);
  
ALTER TABLE CHAINS ADD CONSTRAINT FK_GROUP_ID_2
  FOREIGN KEY (GROUP_ID_2) REFERENCES GROUPS (GROUP_ID);
  
ALTER TABLE GROUPS ADD CONSTRAINT FK_EMPLOYEE_ID_1
  FOREIGN KEY (EMPLOYEE_ID_1) REFERENCES EMPLOYEES (EMPLOYEE_ID);

ALTER TABLE GROUPS ADD CONSTRAINT FK_EMPLOYEE_ID_2
  FOREIGN KEY (EMPLOYEE_ID_2) REFERENCES EMPLOYEES (EMPLOYEE_ID);

ALTER TABLE GROUPS ADD CONSTRAINT FK_EMPLOYEE_ID_3
  FOREIGN KEY (EMPLOYEE_ID_3) REFERENCES EMPLOYEES (EMPLOYEE_ID);

ALTER TABLE GROUPS ADD CONSTRAINT FK_EMPLOYEE_ID_4
  FOREIGN KEY (EMPLOYEE_ID_4) REFERENCES EMPLOYEES (EMPLOYEE_ID);

ALTER TABLE GROUPS ADD CONSTRAINT FK_EMPLOYEE_ID_5
  FOREIGN KEY (EMPLOYEE_ID_5) REFERENCES EMPLOYEES (EMPLOYEE_ID);

ALTER TABLE GROUPS ADD CONSTRAINT FK_EMPLOYEE_ID_6
  FOREIGN KEY (EMPLOYEE_ID_6) REFERENCES EMPLOYEES (EMPLOYEE_ID);
  
ALTER TABLE MAINT_REQS ADD CONSTRAINT FK_MAINT_MESSAGE_ID
  FOREIGN KEY (MESSAGE_ID) REFERENCES MESSAGES (MESSAGE_ID);

ALTER TABLE MAINT_REQS ADD CONSTRAINT FK_MAINT_SENDER_ID
  FOREIGN KEY (SENDER_ID) REFERENCES EMPLOYEES (EMPLOYEE_ID);

ALTER TABLE TRANS_REQS ADD CONSTRAINT FK_TRANS_MESSAGE_ID
  FOREIGN KEY (MESSAGE_ID) REFERENCES MESSAGES (MESSAGE_ID);
  
ALTER TABLE TRANS_REQS ADD CONSTRAINT FK_TRANS_SENDER_ID
  FOREIGN KEY (SENDER_ID) REFERENCES EMPLOYEES (EMPLOYEE_ID);

-- CREATE SEQUENCES --
/
CREATE SEQUENCE APARTMENT_SEQ
  MINVALUE 1
  START WITH    1
  INCREMENT BY  1;
/

CREATE SEQUENCE EMPLOYEE_SEQ
  MINVALUE 1
  START WITH    1
  INCREMENT BY  1;
/

CREATE SEQUENCE MESSAGE_SEQ
  MINVALUE 1
  START WITH    1
  INCREMENT BY  1;
/

CREATE SEQUENCE CHAIN_SEQ
  MINVALUE 1
  START WITH    1
  INCREMENT BY  1;
/

CREATE SEQUENCE GROUP_SEQ
  MINVALUE 1
  START WITH    1
  INCREMENT BY  1;
/

CREATE SEQUENCE TRANS_REQ_SEQ
  MINVALUE 1
  START WITH    1
  INCREMENT BY  1;
/

CREATE SEQUENCE MAINT_REQ_SEQ
  MINVALUE 1
  START WITH    1
  INCREMENT BY  1;
/