//File Name SendEmail.java
package com.revature.web;

import java.util.Properties;

import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.servlet.http.HttpSession;

import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import com.sun.mail.smtp.SMTPMessage;

@RestController
@RequestMapping("/moveOutEmailRest")
public class MoveOutEmailRestController {
	
	@RequestMapping(method=RequestMethod.POST)	
	public @ResponseBody Boolean moveOutEmail_JSON( @RequestBody String moveOutEmail, HttpSession session, ModelMap modelMap){
		
/*		firstName : $scope.empl.employee.firstName,
		lastName : $scope.empl.employee.lastName,
		email : $scope.empl.employee.email,
		address : $scope.empl.employee.address*/
		System.out.println(moveOutEmail);
		
		JsonElement jelement = new JsonParser().parse(moveOutEmail);
		JsonObject jobject = jelement.getAsJsonObject();
		
	   
	    String firstName = jobject.get("firstName").getAsString();
	    String lastName = jobject.get("lastName").getAsString();
	    String recipientEmail = jobject.get("email").getAsString();
	    String address = jobject.get("address").getAsString();
	    
	    String emailPreface = "MOVE OUT ALERT EMAIL \n\n " + 
	    					"--------------------------------- \n\n" +
	    					"Generated by the RCS system\n\n" + 
	    					"Dear " +  firstName + " " + lastName + ", \n\n" + 
	    					"	This is a MOVE OUT ALERT EMAIL indicating that you have 7 days to move " +
	    					"out of your apartment at " + address + "\n\n" +
	    					"Thank you, \n" + 
	    					"HR at revature";
	    
	    boolean result = sendEmail(recipientEmail, "MOVE OUT ALERT EMAIL", emailPreface);
	   
	    
		return result;
	}

	public boolean sendEmail(String recipientEmail, String subject, String body){    
		Properties props = new Properties();
	    props.put("mail.smtp.host", "smtp.gmail.com");
	    props.put("mail.smtp.socketFactory.port", "465");
	    props.put("mail.smtp.socketFactory.class",
	            "javax.net.ssl.SSLSocketFactory");
	    props.put("mail.smtp.auth", "true");
	    props.put("mail.smtp.port", "805");

	    Session session = Session.getDefaultInstance(props,new javax.mail.Authenticator() {
	        @Override
	        protected PasswordAuthentication getPasswordAuthentication() {
	                return new PasswordAuthentication("ResidentCommunicationSystem@gmail.com","rcspassword");
	        }
	    });
	    try {

	        SMTPMessage message = new SMTPMessage(session);
	        message.setFrom(new InternetAddress("ResidentCommunicationSystem@gmail.com"));
	        message.setRecipients(Message.RecipientType.TO,
	                                 InternetAddress.parse(recipientEmail));

	        message.setSubject(subject);
	        message.setText(body);
	        message.setNotifyOptions(SMTPMessage.NOTIFY_SUCCESS);
	        int returnOption = message.getReturnOption();
	        System.out.println(returnOption);        
	        Transport.send(message);
	        System.out.println("sent");
	        return true;

	    }
	     catch (MessagingException e) {
	        return false;
	     }
	}
}